spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/expenses_db}
    username: ${DB_USERNAME:expenses_user}
    password: ${DB_PASSWORD:expenses_pass}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
  thymeleaf:
    cache: false

server:
  port: ${PORT:8080}

app:
  seed:
    user-password: 1234
    admin-password: 1234
